package org.tobi29.scapes.engine.utils.shader.expression;

public enum ConditionType {
    CONDITION_LOGICAL_OR,
    CONDITION_LOGICAL_AND,
    CONDITION_INCLUSIVE_OR,
    CONDITION_EXCLUSIVE_OR,
    CONDITION_AND,
    CONDITION_EQUALS,
    CONDITION_NOT_EQUALS,
    CONDITION_LESS,
    CONDITION_GREATER,
    CONDITION_LESS_EQUAL,
    CONDITION_GREATER_EQUAL
}
